kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: roboshop-efs
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-00d526722b8257eb7
  directoryPerms: "700"
  basePath: "/roboshop"